// Predefined list of majors available at UNC
export const MAJORS_LIST = [
  'Psychology',
  'Economics', 
  'Political Science',
  'Exercise and Sport Science',
  'Neuroscience',
  'Computer Science',
  'Biology',
  'Business Administration',
  'Media and Journalism',
  'Biomedical Engineering',
  'Applied Sciences',
  'Mathematics',
  'Chemistry',
  'Physics',
  'English',
  'History',
  'Sociology',
  'Art',
  'Music',
  'Data Science',
  'Statistics',
  'Communications',
  'Education',
  'Religious Studies'
].sort();