name: Deploy StudySync

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install backend dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Test backend health
      run: |
        cd backend
        python -c "
        import sys
        try:
            from main import app
            from auth_models import User, UserCreate, LoginRequest
            print('✅ Backend imports successful')
        except Exception as e:
            print(f'❌ Backend import failed: {e}')
            sys.exit(1)
        "

  test-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install frontend dependencies
      run: |
        cd frontend
        npm ci
        
    - name: Build frontend
      run: |
        cd frontend
        npm run build
        
    - name: Test build output
      run: |
        cd frontend
        if [ -d "dist" ] && [ -f "dist/index.html" ]; then
          echo "✅ Frontend build successful"
        else
          echo "❌ Frontend build failed"
          exit 1
        fi

  deploy-notification:
    runs-on: ubuntu-latest
    needs: [test-backend, test-frontend]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
    - name: Deployment Ready
      run: |
        echo "🚀 All tests passed! Ready for deployment to:"
        echo "   - Vercel (Frontend): Auto-deploys on push to main"
        echo "   - Railway (Backend): Auto-deploys on push to main"
        echo "   - MongoDB Atlas: No deployment needed"